### ISSUE TITLE
Merge does not work with Region Scanner output

### ISSUE THREAD

**Issue by xieve** [ZigTheHedge/jeargh#2]
I've used [Region Scanner](https://github.com/RundownRhino/RegionScanner) to generate my world-gen.json, and when I try to run jeargh with the merge option, it silently fails (no chat message) and outputs this to the console:
```
[06/12/2023 13:33:17 PM] Exception in thread "Thread-41" java.lang.NullPointerException: Cannot invoke "String.split(String)" because "entry.distrib_raw" is null
[06/12/2023 13:33:17 PM] 	at TRANSFORMER/jeargh@1.19.2-1.0.2/com.cwelth.jeargh.utils.JEARGHProfiler.loadMapFromWorldGen(JEARGHProfiler.java:162)
[06/12/2023 13:33:17 PM] 	at TRANSFORMER/jeargh@1.19.2-1.0.2/com.cwelth.jeargh.utils.JEARGHProfiler.run(JEARGHProfiler.java:265)
[06/12/2023 13:33:17 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
```
Not sure if this is even the intended use-case of the merge feature? A bit more documentation on that would be very nice.

[world-gen.json](https://github.com/ZigTheHedge/jeargh/files/13582961/world-gen.json)

**Comment by ZigTheHedge** [comment]
"merge" is needed when you want to profile specified parts of the world. For example - high hills or underground caves. It uses additional data in world-gen.json, which is not provided by Region Scanner for obvious reasons :)

**Comment by xieve** [comment]
That makes sense, thank you :) I wrote a small python script to do what I had expected the merge option to do, in case anybody else wants to do this: https://gist.github.com/xieve/36e69c4379e30358f05720965d2685f1
Region Scanner covers a larger area in smaller time but doesn't compute drops, so this seems like a good mix to me.
